import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Frontend Face Recognition",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <nav className="flex justify-around mx-auto py-4 border-b-2 fixed bg-white w-full top-0 font-semibold ">
          <div>Logo</div>
          <div className="flex gap-4 ">
              <Link href="/order">Cari Foto</Link>
              <Link href="/">Events</Link>
              <Link href="/">Tentang Kami</Link>
          </div>
          <div className="flex gap-4">
              <Link href="/">Login</Link>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
